# These are supported funding model platforms

github:[devvorldtech]
patreon: devvorldtech
open_collective: devvorldtech
ko_fi: https://ko-fi.com/devvorld

liberapay: devvorldtech
issuehunt: devvorldtech

